# Generated by Django 5.0.1 on 2025-07-23 23:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='raw_data',
        ),
        migrations.AddField(
            model_name='character',
            name='a',
            field=models.IntegerField(default=0, help_text='a'),
        ),
        migrations.AddField(
            model_name='character',
            name='ac_bk_hip',
            field=models.JSONField(blank=True, default=dict, help_text='ACBkHip'),
        ),
        migrations.AddField(
            model_name='character',
            name='ac_ft_hip',
            field=models.JSONField(blank=True, default=dict, help_text='ACFtHip'),
        ),
        migrations.AddField(
            model_name='character',
            name='ac_lt_ankle',
            field=models.JSONField(blank=True, default=dict, help_text='ACLtAnkle'),
        ),
        migrations.AddField(
            model_name='character',
            name='ac_lt_arm',
            field=models.JSONField(blank=True, default=dict, help_text='ACLtArm'),
        ),
        migrations.AddField(
            model_name='character',
            name='ac_lt_bracer',
            field=models.JSONField(blank=True, default=dict, help_text='ACLtBracer'),
        ),
        migrations.AddField(
            model_name='character',
            name='ac_lt_elbow',
            field=models.JSONField(blank=True, default=dict, help_text='ACLtElbow'),
        ),
        migrations.AddField(
            model_name='character',
            name='ac_lt_foot',
            field=models.JSONField(blank=True, default=dict, help_text='ACLtFoot'),
        ),
        migrations.AddField(
            model_name='character',
            name='ac_lt_hip',
            field=models.JSONField(blank=True, default=dict, help_text='ACLtHip'),
        ),
        migrations.AddField(
            model_name='character',
            name='ac_lt_knee',
            field=models.JSONField(blank=True, default=dict, help_text='ACLtKnee'),
        ),
        migrations.AddField(
            model_name='character',
            name='ac_lt_leg',
            field=models.JSONField(blank=True, default=dict, help_text='ACLtLeg'),
        ),
        migrations.AddField(
            model_name='character',
            name='ac_lt_shin',
            field=models.JSONField(blank=True, default=dict, help_text='ACLtShin'),
        ),
        migrations.AddField(
            model_name='character',
            name='ac_lt_shoulder',
            field=models.JSONField(blank=True, default=dict, help_text='ACLtShoulder'),
        ),
        migrations.AddField(
            model_name='character',
            name='ac_rt_ankle',
            field=models.JSONField(blank=True, default=dict, help_text='ACRtAnkle'),
        ),
        migrations.AddField(
            model_name='character',
            name='ac_rt_arm',
            field=models.JSONField(blank=True, default=dict, help_text='ACRtArm'),
        ),
        migrations.AddField(
            model_name='character',
            name='ac_rt_bracer',
            field=models.JSONField(blank=True, default=dict, help_text='ACRtBracer'),
        ),
        migrations.AddField(
            model_name='character',
            name='ac_rt_elbow',
            field=models.JSONField(blank=True, default=dict, help_text='ACRtElbow'),
        ),
        migrations.AddField(
            model_name='character',
            name='ac_rt_foot',
            field=models.JSONField(blank=True, default=dict, help_text='ACRtFoot'),
        ),
        migrations.AddField(
            model_name='character',
            name='ac_rt_hip',
            field=models.JSONField(blank=True, default=dict, help_text='ACRtHip'),
        ),
        migrations.AddField(
            model_name='character',
            name='ac_rt_knee',
            field=models.JSONField(blank=True, default=dict, help_text='ACRtKnee'),
        ),
        migrations.AddField(
            model_name='character',
            name='ac_rt_leg',
            field=models.JSONField(blank=True, default=dict, help_text='ACRtLeg'),
        ),
        migrations.AddField(
            model_name='character',
            name='ac_rt_shin',
            field=models.JSONField(blank=True, default=dict, help_text='ACRtShin'),
        ),
        migrations.AddField(
            model_name='character',
            name='ac_rt_shoulder',
            field=models.JSONField(blank=True, default=dict, help_text='ACRtShoulder'),
        ),
        migrations.AddField(
            model_name='character',
            name='action_list',
            field=models.JSONField(blank=True, default=dict, help_text='ActionList'),
        ),
        migrations.AddField(
            model_name='character',
            name='alwys_prcvbl',
            field=models.IntegerField(default=0, help_text='AlwysPrcvbl'),
        ),
        migrations.AddField(
            model_name='character',
            name='ambient_anim_state',
            field=models.IntegerField(default=0, help_text='AmbientAnimState'),
        ),
        migrations.AddField(
            model_name='character',
            name='animation_day',
            field=models.IntegerField(default=461152, help_text='AnimationDay'),
        ),
        migrations.AddField(
            model_name='character',
            name='animation_time',
            field=models.IntegerField(default=1148714, help_text='AnimationTime'),
        ),
        migrations.AddField(
            model_name='character',
            name='appearance_f_hair',
            field=models.IntegerField(default=0, help_text='Appearance_FHair'),
        ),
        migrations.AddField(
            model_name='character',
            name='appearance_hair',
            field=models.IntegerField(default=0, help_text='Appearance_Hair'),
        ),
        migrations.AddField(
            model_name='character',
            name='appearance_head',
            field=models.IntegerField(default=0, help_text='Appearance_Head'),
        ),
        migrations.AddField(
            model_name='character',
            name='appearance_sef',
            field=models.CharField(blank=True, default='', help_text='AppearanceSEF', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='appearance_type',
            field=models.IntegerField(default=0, help_text='Appearance_Type'),
        ),
        migrations.AddField(
            model_name='character',
            name='area_id',
            field=models.IntegerField(default=5012, help_text='AreaId'),
        ),
        migrations.AddField(
            model_name='character',
            name='armor_tint',
            field=models.JSONField(blank=True, default=dict, help_text='ArmorTint'),
        ),
        migrations.AddField(
            model_name='character',
            name='armor_visual_type',
            field=models.IntegerField(default=0, help_text='ArmorVisualType'),
        ),
        migrations.AddField(
            model_name='character',
            name='associate_list',
            field=models.JSONField(blank=True, default=dict, help_text='AssociateList'),
        ),
        migrations.AddField(
            model_name='character',
            name='attack_result',
            field=models.IntegerField(default=0, help_text='AttackResult'),
        ),
        migrations.AddField(
            model_name='character',
            name='b',
            field=models.IntegerField(default=0, help_text='b'),
        ),
        migrations.AddField(
            model_name='character',
            name='base_attack_bonus',
            field=models.IntegerField(default=0, help_text='BaseAttackBonus'),
        ),
        migrations.AddField(
            model_name='character',
            name='block_broadcast',
            field=models.IntegerField(default=0, help_text='BlockBroadcast'),
        ),
        migrations.AddField(
            model_name='character',
            name='block_combat',
            field=models.IntegerField(default=0, help_text='BlockCombat'),
        ),
        migrations.AddField(
            model_name='character',
            name='block_respond',
            field=models.IntegerField(default=0, help_text='BlockRespond'),
        ),
        migrations.AddField(
            model_name='character',
            name='body_bag',
            field=models.IntegerField(default=0, help_text='BodyBag'),
        ),
        migrations.AddField(
            model_name='character',
            name='body_bag_id',
            field=models.IntegerField(default=2130706432, help_text='BodyBagId'),
        ),
        migrations.AddField(
            model_name='character',
            name='boots',
            field=models.JSONField(blank=True, default=dict, help_text='Boots'),
        ),
        migrations.AddField(
            model_name='character',
            name='bump_state',
            field=models.IntegerField(default=0, help_text='BumpState'),
        ),
        migrations.AddField(
            model_name='character',
            name='challenge_rating',
            field=models.FloatField(default=0.0, help_text='ChallengeRating'),
        ),
        migrations.AddField(
            model_name='character',
            name='char_background',
            field=models.IntegerField(default=0, help_text='CharBackground'),
        ),
        migrations.AddField(
            model_name='character',
            name='character_class',
            field=models.IntegerField(default=0, help_text='Class'),
        ),
        migrations.AddField(
            model_name='character',
            name='class_level',
            field=models.IntegerField(default=0, help_text='ClassLevel'),
        ),
        migrations.AddField(
            model_name='character',
            name='color_tattoo1',
            field=models.IntegerField(default=0, help_text='Color_Tattoo1'),
        ),
        migrations.AddField(
            model_name='character',
            name='color_tattoo2',
            field=models.IntegerField(default=0, help_text='Color_Tattoo2'),
        ),
        migrations.AddField(
            model_name='character',
            name='combat_info',
            field=models.JSONField(blank=True, default=dict, help_text='CombatInfo'),
        ),
        migrations.AddField(
            model_name='character',
            name='combat_mode',
            field=models.IntegerField(default=0, help_text='CombatMode'),
        ),
        migrations.AddField(
            model_name='character',
            name='combat_round_data',
            field=models.JSONField(blank=True, default=dict, help_text='CombatRoundData'),
        ),
        migrations.AddField(
            model_name='character',
            name='companion_name',
            field=models.CharField(blank=True, default='', help_text='CompanionName', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='companion_type',
            field=models.IntegerField(default=0, help_text='CompanionType'),
        ),
        migrations.AddField(
            model_name='character',
            name='conjure_sound_tag',
            field=models.CharField(blank=True, default='', help_text='ConjureSoundTag', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='conversation',
            field=models.CharField(blank=True, default='', help_text='Conversation', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='creatn_scrpt_fird',
            field=models.IntegerField(default=0, help_text='CreatnScrptFird'),
        ),
        migrations.AddField(
            model_name='character',
            name='creature_size',
            field=models.IntegerField(default=0, help_text='CreatureSize'),
        ),
        migrations.AddField(
            model_name='character',
            name='creature_version',
            field=models.IntegerField(default=0, help_text='CreatureVersion'),
        ),
        migrations.AddField(
            model_name='character',
            name='crtr_casts_shadow',
            field=models.IntegerField(default=0, help_text='CrtrCastsShadow'),
        ),
        migrations.AddField(
            model_name='character',
            name='crtr_rcv_shadow',
            field=models.IntegerField(default=0, help_text='CrtrRcvShadow'),
        ),
        migrations.AddField(
            model_name='character',
            name='current_hit_points',
            field=models.IntegerField(default=0, help_text='CurrentHitPoints'),
        ),
        migrations.AddField(
            model_name='character',
            name='custom_heartbeat',
            field=models.IntegerField(default=0, help_text='CustomHeartbeat'),
        ),
        migrations.AddField(
            model_name='character',
            name='custom_portrait',
            field=models.CharField(blank=True, default='', help_text='CustomPortrait', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='damage_max',
            field=models.IntegerField(default=0, help_text='DamageMax'),
        ),
        migrations.AddField(
            model_name='character',
            name='damage_min',
            field=models.IntegerField(default=0, help_text='DamageMin'),
        ),
        migrations.AddField(
            model_name='character',
            name='dead_selectable',
            field=models.IntegerField(default=0, help_text='DeadSelectable'),
        ),
        migrations.AddField(
            model_name='character',
            name='decay_time',
            field=models.IntegerField(default=5000, help_text='DecayTime'),
        ),
        migrations.AddField(
            model_name='character',
            name='def_cast_mode',
            field=models.IntegerField(default=0, help_text='DefCastMode'),
        ),
        migrations.AddField(
            model_name='character',
            name='description',
            field=models.JSONField(blank=True, default=dict, help_text='Description'),
        ),
        migrations.AddField(
            model_name='character',
            name='detect_mode',
            field=models.IntegerField(default=0, help_text='DetectMode'),
        ),
        migrations.AddField(
            model_name='character',
            name='disable_ai_hidden',
            field=models.IntegerField(default=0, help_text='DisableAIHidden'),
        ),
        migrations.AddField(
            model_name='character',
            name='disarmable',
            field=models.IntegerField(default=0, help_text='Disarmable'),
        ),
        migrations.AddField(
            model_name='character',
            name='dmg_reduction',
            field=models.JSONField(blank=True, default=dict, help_text='DmgReduction'),
        ),
        migrations.AddField(
            model_name='character',
            name='domain1',
            field=models.IntegerField(default=0, help_text='Domain1'),
        ),
        migrations.AddField(
            model_name='character',
            name='domain2',
            field=models.IntegerField(default=0, help_text='Domain2'),
        ),
        migrations.AddField(
            model_name='character',
            name='effect_list',
            field=models.JSONField(blank=True, default=dict, help_text='EffectList'),
        ),
        migrations.AddField(
            model_name='character',
            name='enh_vision_mode',
            field=models.IntegerField(default=0, help_text='EnhVisionMode'),
        ),
        migrations.AddField(
            model_name='character',
            name='expression_list',
            field=models.JSONField(blank=True, default=dict, help_text='ExpressionList'),
        ),
        migrations.AddField(
            model_name='character',
            name='faction_id',
            field=models.IntegerField(default=0, help_text='FactionID'),
        ),
        migrations.AddField(
            model_name='character',
            name='familiar_name',
            field=models.CharField(blank=True, default='', help_text='FamiliarName', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='familiar_type',
            field=models.IntegerField(default=0, help_text='FamiliarType'),
        ),
        migrations.AddField(
            model_name='character',
            name='fortbonus',
            field=models.IntegerField(default=0, help_text='fortbonus'),
        ),
        migrations.AddField(
            model_name='character',
            name='g',
            field=models.IntegerField(default=0, help_text='g'),
        ),
        migrations.AddField(
            model_name='character',
            name='hlfr_blst_mode',
            field=models.IntegerField(default=0, help_text='HlfrBlstMode'),
        ),
        migrations.AddField(
            model_name='character',
            name='hlfr_shld_mode',
            field=models.IntegerField(default=0, help_text='HlfrShldMode'),
        ),
        migrations.AddField(
            model_name='character',
            name='hotbar_list',
            field=models.JSONField(blank=True, default=dict, help_text='HotbarList'),
        ),
        migrations.AddField(
            model_name='character',
            name='ignore_target',
            field=models.IntegerField(default=0, help_text='IgnoreTarget'),
        ),
        migrations.AddField(
            model_name='character',
            name='interruptable',
            field=models.IntegerField(default=0, help_text='Interruptable'),
        ),
        migrations.AddField(
            model_name='character',
            name='is_commandable',
            field=models.IntegerField(default=0, help_text='IsCommandable'),
        ),
        migrations.AddField(
            model_name='character',
            name='is_destroyable',
            field=models.IntegerField(default=0, help_text='IsDestroyable'),
        ),
        migrations.AddField(
            model_name='character',
            name='is_dm',
            field=models.IntegerField(default=0, help_text='IsDM'),
        ),
        migrations.AddField(
            model_name='character',
            name='is_immortal',
            field=models.IntegerField(default=0, help_text='IsImmortal'),
        ),
        migrations.AddField(
            model_name='character',
            name='is_pc',
            field=models.IntegerField(default=0, help_text='IsPC'),
        ),
        migrations.AddField(
            model_name='character',
            name='is_raiseable',
            field=models.IntegerField(default=0, help_text='IsRaiseable'),
        ),
        migrations.AddField(
            model_name='character',
            name='listening',
            field=models.IntegerField(default=0, help_text='Listening'),
        ),
        migrations.AddField(
            model_name='character',
            name='lootable',
            field=models.IntegerField(default=0, help_text='Lootable'),
        ),
        migrations.AddField(
            model_name='character',
            name='m_class_lev_up_in',
            field=models.IntegerField(default=0, help_text='MClassLevUpIn'),
        ),
        migrations.AddField(
            model_name='character',
            name='master_id',
            field=models.IntegerField(default=2130706432, help_text='MasterID'),
        ),
        migrations.AddField(
            model_name='character',
            name='mod_commnty_id',
            field=models.CharField(blank=True, default='', help_text='Mod_CommntyId', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='mod_commnty_name',
            field=models.CharField(blank=True, default='', help_text='Mod_CommntyName', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='mod_commnty_platf',
            field=models.IntegerField(default=0, help_text='Mod_CommntyPlatf (stored as ASCII value)'),
        ),
        migrations.AddField(
            model_name='character',
            name='mod_is_primary_plr',
            field=models.IntegerField(default=0, help_text='Mod_IsPrimaryPlr'),
        ),
        migrations.AddField(
            model_name='character',
            name='mod_last_mod_id',
            field=models.CharField(blank=True, default='', help_text='Mod_LastModId', max_length=128),
        ),
        migrations.AddField(
            model_name='character',
            name='mod_module_list',
            field=models.JSONField(blank=True, default=dict, help_text='Mod_ModuleList'),
        ),
        migrations.AddField(
            model_name='character',
            name='model_scale',
            field=models.JSONField(blank=True, default=dict, help_text='ModelScale'),
        ),
        migrations.AddField(
            model_name='character',
            name='movement_rate',
            field=models.IntegerField(default=0, help_text='MovementRate'),
        ),
        migrations.AddField(
            model_name='character',
            name='natural_ac',
            field=models.IntegerField(default=0, help_text='NaturalAC'),
        ),
        migrations.AddField(
            model_name='character',
            name='never_draw_helmet',
            field=models.IntegerField(default=0, help_text='NeverDrawHelmet'),
        ),
        migrations.AddField(
            model_name='character',
            name='never_show_armor',
            field=models.IntegerField(default=0, help_text='NeverShowArmor'),
        ),
        migrations.AddField(
            model_name='character',
            name='no_perm_death',
            field=models.IntegerField(default=0, help_text='NoPermDeath'),
        ),
        migrations.AddField(
            model_name='character',
            name='object_id',
            field=models.IntegerField(default=2147483647, help_text='ObjectId'),
        ),
        migrations.AddField(
            model_name='character',
            name='off_hand_attacks',
            field=models.IntegerField(default=0, help_text='OffHandAttacks'),
        ),
        migrations.AddField(
            model_name='character',
            name='oid_target',
            field=models.IntegerField(default=2130706432, help_text='oidTarget'),
        ),
        migrations.AddField(
            model_name='character',
            name='on_hand_attacks',
            field=models.IntegerField(default=0, help_text='OnHandAttacks'),
        ),
        migrations.AddField(
            model_name='character',
            name='orient_on_dialog',
            field=models.IntegerField(default=0, help_text='OrientOnDialog'),
        ),
        migrations.AddField(
            model_name='character',
            name='origin_attacked',
            field=models.CharField(blank=True, default='', help_text='OriginAttacked', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='origin_damaged',
            field=models.CharField(blank=True, default='', help_text='OriginDamaged', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='origin_death',
            field=models.CharField(blank=True, default='', help_text='OriginDeath', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='origin_dialogue',
            field=models.CharField(blank=True, default='', help_text='OriginDialogue', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='origin_disturbed',
            field=models.CharField(blank=True, default='', help_text='OriginDisturbed', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='origin_end_round',
            field=models.CharField(blank=True, default='', help_text='OriginEndRound', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='origin_heartbeat',
            field=models.CharField(blank=True, default='', help_text='OriginHeartbeat', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='origin_on_blocked',
            field=models.CharField(blank=True, default='', help_text='OriginOnBlocked', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='origin_on_notice',
            field=models.CharField(blank=True, default='', help_text='OriginOnNotice', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='origin_rested',
            field=models.CharField(blank=True, default='', help_text='OriginRested', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='origin_spawn',
            field=models.CharField(blank=True, default='', help_text='OriginSpawn', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='origin_spell_at',
            field=models.CharField(blank=True, default='', help_text='OriginSpellAt', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='origin_user_define',
            field=models.CharField(blank=True, default='', help_text='OriginUserDefine', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='override_bab',
            field=models.IntegerField(default=0, help_text='OverrideBAB'),
        ),
        migrations.AddField(
            model_name='character',
            name='override_bab_min',
            field=models.IntegerField(default=0, help_text='OverrideBABMin'),
        ),
        migrations.AddField(
            model_name='character',
            name='p_m_is_polymorphed',
            field=models.IntegerField(default=0, help_text='PM_IsPolymorphed'),
        ),
        migrations.AddField(
            model_name='character',
            name='perception_list',
            field=models.JSONField(blank=True, default=dict, help_text='PerceptionList'),
        ),
        migrations.AddField(
            model_name='character',
            name='perception_range',
            field=models.IntegerField(default=0, help_text='PerceptionRange'),
        ),
        migrations.AddField(
            model_name='character',
            name='personal_rep_list',
            field=models.JSONField(blank=True, default=dict, help_text='PersonalRepList'),
        ),
        migrations.AddField(
            model_name='character',
            name='plot',
            field=models.IntegerField(default=0, help_text='Plot'),
        ),
        migrations.AddField(
            model_name='character',
            name='portrait',
            field=models.CharField(blank=True, default='', help_text='Portrait', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='poss_blocked',
            field=models.IntegerField(default=0, help_text='PossBlocked'),
        ),
        migrations.AddField(
            model_name='character',
            name='pregame_current',
            field=models.IntegerField(default=0, help_text='PregameCurrent'),
        ),
        migrations.AddField(
            model_name='character',
            name='r',
            field=models.IntegerField(default=0, help_text='r'),
        ),
        migrations.AddField(
            model_name='character',
            name='refbonus',
            field=models.IntegerField(default=0, help_text='refbonus'),
        ),
        migrations.AddField(
            model_name='character',
            name='roster_member',
            field=models.IntegerField(default=0, help_text='RosterMember'),
        ),
        migrations.AddField(
            model_name='character',
            name='roster_tag',
            field=models.CharField(blank=True, default='', help_text='RosterTag', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='script_attacked',
            field=models.CharField(blank=True, default='', help_text='ScriptAttacked', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='script_damaged',
            field=models.CharField(blank=True, default='', help_text='ScriptDamaged', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='script_death',
            field=models.CharField(blank=True, default='', help_text='ScriptDeath', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='script_dialogue',
            field=models.CharField(blank=True, default='', help_text='ScriptDialogue', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='script_disturbed',
            field=models.CharField(blank=True, default='', help_text='ScriptDisturbed', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='script_end_round',
            field=models.CharField(blank=True, default='', help_text='ScriptEndRound', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='script_heartbeat',
            field=models.CharField(blank=True, default='', help_text='ScriptHeartbeat', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='script_hidden',
            field=models.IntegerField(default=0, help_text='ScriptHidden'),
        ),
        migrations.AddField(
            model_name='character',
            name='script_on_blocked',
            field=models.CharField(blank=True, default='', help_text='ScriptOnBlocked', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='script_on_notice',
            field=models.CharField(blank=True, default='', help_text='ScriptOnNotice', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='script_rested',
            field=models.CharField(blank=True, default='', help_text='ScriptRested', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='script_spawn',
            field=models.CharField(blank=True, default='', help_text='ScriptSpawn', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='script_spell_at',
            field=models.CharField(blank=True, default='', help_text='ScriptSpellAt', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='script_user_define',
            field=models.CharField(blank=True, default='', help_text='ScriptUserDefine', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='scripts_bckd_up',
            field=models.IntegerField(default=0, help_text='ScriptsBckdUp'),
        ),
        migrations.AddField(
            model_name='character',
            name='sit_object',
            field=models.IntegerField(default=2130706432, help_text='SitObject'),
        ),
        migrations.AddField(
            model_name='character',
            name='skill_points',
            field=models.IntegerField(default=0, help_text='SkillPoints'),
        ),
        migrations.AddField(
            model_name='character',
            name='sound_set_file',
            field=models.IntegerField(default=0, help_text='SoundSetFile'),
        ),
        migrations.AddField(
            model_name='character',
            name='spirit_override',
            field=models.IntegerField(default=0, help_text='SpiritOverride'),
        ),
        migrations.AddField(
            model_name='character',
            name='starting_package',
            field=models.IntegerField(default=0, help_text='StartingPackage'),
        ),
        migrations.AddField(
            model_name='character',
            name='stealth_mode',
            field=models.IntegerField(default=0, help_text='StealthMode'),
        ),
        migrations.AddField(
            model_name='character',
            name='tag',
            field=models.CharField(blank=True, default='', help_text='Tag', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='tail',
            field=models.IntegerField(default=0, help_text='Tail'),
        ),
        migrations.AddField(
            model_name='character',
            name='talk_player_own',
            field=models.IntegerField(default=0, help_text='TalkPlayerOwn'),
        ),
        migrations.AddField(
            model_name='character',
            name='template_res_ref',
            field=models.CharField(blank=True, default='', help_text='TemplateResRef', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='tint_hair',
            field=models.JSONField(blank=True, default=dict, help_text='Tint_Hair'),
        ),
        migrations.AddField(
            model_name='character',
            name='tint_head',
            field=models.JSONField(blank=True, default=dict, help_text='Tint_Head'),
        ),
        migrations.AddField(
            model_name='character',
            name='tintable',
            field=models.JSONField(blank=True, default=dict, help_text='Tintable'),
        ),
        migrations.AddField(
            model_name='character',
            name='tracking_mode',
            field=models.IntegerField(default=0, help_text='TrackingMode'),
        ),
        migrations.AddField(
            model_name='character',
            name='unrestrict_lu',
            field=models.IntegerField(default=0, help_text='UnrestrictLU'),
        ),
        migrations.AddField(
            model_name='character',
            name='uv_scroll',
            field=models.JSONField(blank=True, default=dict, help_text='UVScroll'),
        ),
        migrations.AddField(
            model_name='character',
            name='var_table',
            field=models.JSONField(blank=True, default=dict, help_text='VarTable'),
        ),
        migrations.AddField(
            model_name='character',
            name='variation',
            field=models.IntegerField(default=0, help_text='Variation'),
        ),
        migrations.AddField(
            model_name='character',
            name='willbonus',
            field=models.IntegerField(default=0, help_text='willbonus'),
        ),
        migrations.AddField(
            model_name='character',
            name='wings',
            field=models.IntegerField(default=0, help_text='Wings'),
        ),
        migrations.AddField(
            model_name='character',
            name='x_orientation',
            field=models.FloatField(default=-0.1, help_text='XOrientation'),
        ),
        migrations.AddField(
            model_name='character',
            name='x_position',
            field=models.FloatField(default=98.7, help_text='XPosition'),
        ),
        migrations.AddField(
            model_name='character',
            name='xp_mod',
            field=models.FloatField(default=1.0, help_text='XpMod'),
        ),
        migrations.AddField(
            model_name='character',
            name='y_orientation',
            field=models.FloatField(default=1.0, help_text='YOrientation'),
        ),
        migrations.AddField(
            model_name='character',
            name='y_position',
            field=models.FloatField(default=135.1, help_text='YPosition'),
        ),
        migrations.AddField(
            model_name='character',
            name='z_orientation',
            field=models.FloatField(default=0.0, help_text='ZOrientation'),
        ),
        migrations.AddField(
            model_name='character',
            name='z_position',
            field=models.FloatField(default=-0.0, help_text='ZPosition'),
        ),
        migrations.AlterField(
            model_name='character',
            name='age',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='character',
            name='character_level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='file_path',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='character',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='character',
            name='race_id',
            field=models.IntegerField(default=0),
        ),
    ]
