# Generated by Django 5.0.1 on 2025-07-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_remove_character_raw_data_character_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='custom_content_ids',
            field=models.JSONField(blank=True, default=dict, help_text='IDs of custom content used by this character'),
        ),
        migrations.AddField(
            model_name='character',
            name='module_hakpaks',
            field=models.JSONField(blank=True, default=list, help_text='List of hakpaks from module.ifo'),
        ),
        migrations.AddField(
            model_name='character',
            name='module_name',
            field=models.CharField(blank=True, help_text='Module this save is from (e.g., MotB_Campaign)', max_length=255),
        ),
        migrations.AddField(
            model_name='character',
            name='uses_custom_content',
            field=models.BooleanField(default=False, help_text='Whether this character uses module-specific content'),
        ),
    ]
