# Generated by Django 5.0.1 on 2025-07-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_add_module_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='is_savegame',
            field=models.BooleanField(default=False, help_text='Whether this is from a save game (vs standalone .bic)'),
        ),
    ]
