# Generated by Django 4.0 on 2025-07-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_character_is_savegame'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='campaign_level_cap',
            field=models.IntegerField(blank=True, help_text='Campaign level cap', null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='campaign_modules',
            field=models.JSONField(blank=True, default=list, help_text='List of modules in the campaign'),
        ),
        migrations.AddField(
            model_name='character',
            name='campaign_name',
            field=models.CharField(blank=True, help_text='Campaign this character is from (e.g., Original Campaign, MotB)', max_length=255),
        ),
        migrations.AddField(
            model_name='character',
            name='campaign_path',
            field=models.CharField(blank=True, help_text='Path to the campaign directory', max_length=500),
        ),
    ]
