# Generated by Django 5.0.1 on 2025-07-27 19:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0006_fix_character_data_for_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='character',
            constraint=models.CheckConstraint(check=models.Q(('law_chaos__gte', 0), ('law_chaos__lte', 100)), name='valid_law_chaos'),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.CheckConstraint(check=models.Q(('good_evil__gte', 0), ('good_evil__lte', 100)), name='valid_good_evil'),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.CheckConstraint(check=models.Q(('character_level__gte', 1), ('character_level__lte', 40)), name='valid_character_level'),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.CheckConstraint(check=models.Q(('strength__gte', 3), ('strength__lte', 50)), name='valid_strength'),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.CheckConstraint(check=models.Q(('dexterity__gte', 3), ('dexterity__lte', 50)), name='valid_dexterity'),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.CheckConstraint(check=models.Q(('constitution__gte', 3), ('constitution__lte', 50)), name='valid_constitution'),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.CheckConstraint(check=models.Q(('intelligence__gte', 3), ('intelligence__lte', 50)), name='valid_intelligence'),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.CheckConstraint(check=models.Q(('wisdom__gte', 3), ('wisdom__lte', 50)), name='valid_wisdom'),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.CheckConstraint(check=models.Q(('charisma__gte', 3), ('charisma__lte', 50)), name='valid_charisma'),
        ),
    ]
