# Generated by Django 5.0.1 on 2025-07-31 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0007_add_character_improvements'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='character',
            name='valid_law_chaos',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='valid_good_evil',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='valid_character_level',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='valid_strength',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='valid_dexterity',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='valid_constitution',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='valid_intelligence',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='valid_wisdom',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='valid_charisma',
        ),
        migrations.AddField(
            model_name='character',
            name='is_cheated',
            field=models.BooleanField(default=False, help_text='Whether this character has invalid/cheated values'),
        ),
        migrations.AlterField(
            model_name='character',
            name='character_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='charisma',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='constitution',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='dexterity',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='good_evil',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='intelligence',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='law_chaos',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='strength',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='wisdom',
            field=models.IntegerField(default=10),
        ),
    ]
