# Generated by Django 5.0.1 on 2025-07-31 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0008_add_is_cheated_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='is_cheated',
        ),
    ]
