# Generated by Django 5.0.1 on 2025-08-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0009_remove_is_cheated_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='active_quests_count',
            field=models.IntegerField(default=0, help_text='Number of active quests'),
        ),
        migrations.AddField(
            model_name='character',
            name='companion_influence',
            field=models.JSONField(blank=True, default=dict, help_text='Companion influence levels'),
        ),
        migrations.AddField(
            model_name='character',
            name='completed_quests_count',
            field=models.IntegerField(default=0, help_text='Number of completed quests'),
        ),
        migrations.AddField(
            model_name='character',
            name='current_area',
            field=models.CharField(blank=True, help_text='Current area/module from currentmodule.txt', max_length=255),
        ),
        migrations.AddField(
            model_name='character',
            name='unlocked_locations',
            field=models.JSONField(blank=True, default=list, help_text='Unlocked world map locations'),
        ),
    ]
