# Generated by Django 5.0.1 on 2025-08-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0010_character_active_quests_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='companion_status',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed companion status: influence, joined, met'),
        ),
        migrations.AddField(
            model_name='character',
            name='difficulty_level',
            field=models.IntegerField(blank=True, help_text='Game difficulty level', null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='game_act',
            field=models.IntegerField(blank=True, help_text='Current game act (1, 2, 3, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='hidden_statistics',
            field=models.JSONField(blank=True, default=dict, help_text='Hidden gameplay stats: dialogue choices, etc.'),
        ),
        migrations.AddField(
            model_name='character',
            name='last_saved_timestamp',
            field=models.BigIntegerField(blank=True, help_text='Unix timestamp of last save', null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='story_milestones',
            field=models.JSONField(blank=True, default=dict, help_text='Major story progression milestones'),
        ),
    ]
