# Generated by Django 5.0.1 on 2025-08-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0011_character_companion_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='quest_details',
            field=models.JSONField(blank=True, default=dict, help_text='Enhanced quest information with categories and progress'),
        ),
    ]
