# Generated by Django 5.0.1 on 2025-08-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameclass',
            name='int',
            field=models.IntegerField(db_column='int', default=0, help_text='Int'),
        ),
        migrations.RenameField(
            model_name='gameclass',
            old_name='int',
            new_name='int_value',
        ),
        migrations.AlterField(
            model_name='gameclass',
            name='wis',
            field=models.IntegerField(default=0, help_text='Wis'),
        ),
        migrations.AlterField(
            model_name='race',
            name='wis_adjust',
            field=models.IntegerField(default=0, help_text='WisAdjust'),
        ),
        migrations.AlterField(
            model_name='subrace',
            name='wis_adjust',
            field=models.IntegerField(default=0, help_text='WisAdjust'),
        ),
    ]
